services:
  claude-code:
    build:
      context: .
      dockerfile: debian-stable-slim.Dockerfile

  opencode:
    build:
      context: .
      dockerfile: debian-stable-slim.Dockerfile

  pi:
    build:
      context: .
      dockerfile: debian-testing-slim.Dockerfile
